### ISSUE TITLE
JavaScript Version and gh-pages

### ISSUE THREAD

**Issue by arrowrowe** [arrowrowe/github-relationship#1]
Complete JavaScript version on a new branch, gh-pages, for convenient preview.

Request sample:
- [JSON-P Callbacks | GitHub API v3](https://developer.github.com/v3/#json-p-callbacks)

Visualization sample:
- [Force-Directed Graph | D3 Gallery](http://bl.ocks.org/mbostock/4062045)
- [Collapsible Force Layout | D3 Gallery](http://mbostock.github.io/d3/talk/20111116/force-collapsible.html)

Great works:
- [artzub/GitHubVisualizer](https://github.com/artzub/GitHubVisualizer)

**Comment by arrowrowe** [comment]
Current JavaScript version 09bf77a86fb5c1bbe243b36a5b8c6f97927790b8 only has hardcoded data.

Todo: fetch real-time data by API.

**Comment by at15** [comment]
current js demo is just using data.json file instead of making calls to GitHub api.

**Comment by arrowrowe** [comment]
re @at15: yes, cause using GitHub API without proper limitation is not recommended......

**Comment by arrowrowe** [comment]
Probably no update recently. So close.

**Comment by at15** [comment]
@arrowrowe pia
